name: Build
on:
  pull_request:
    branches:
      - main

env:
  NIXPKGS_ALLOW_BROKEN: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          # Fixes: https://github.com/cachix/cachix-action/issues/138
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v12
        with:
          name: cachix-action
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix --log-format raw -L build .#defaultDockerContainer.x86_64-linux --impure
